<?php

use Illuminate\Database\Seeder;

class BanksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $banks = [
            'aceh_syar' => 'PT. BPD Istimewa Aceh Syariah',
            'agris' => 'PT. Bank Agris',
            'agroniaga' => 'PT. Agroniaga Bank',
            'akita' => 'PT. Bank Akita',
            'andara' => 'PT. Bank Andara',
            'anglomas' => 'PT. Anglomas International Bank',
            'antar_daerah' => 'PT. Bank Antar Daerah',
            'anz' => 'PT. ANZ Panin Bank',
            'artajasa' => 'PT. Artajasa',
            'artha' => 'PT. Bank Artha Graha International',
            'artos' => 'PT. Bank Artos Indonesia',
            'bali' => 'PT. BPD Bali',
            'bangkok' => 'The Bangkok Bank PCLa',
            'bca' => 'PT. Bank Central Asia Tbk.',
            'bca_syar' => 'PT. Bank BCA Syariah',
            'bengkulu' => 'PT. BPD Bengkulu',
            'bjb' => 'PT. Bank Jabar dan Banten',
            'bni' => 'PT. BNI 1946 (Persero) Tbk.',
            'bni_syar' => 'PT. Bank BNI Syariah',
            'bnp' => 'PT. Bank Nusantara Parahyangan',
            'bnp_paribas' => 'PT. Bank BNP Paribas Indonesia',
            'boa' => 'Bank of America NA',
            'bri' => 'PT. BRI (Persero) Tbk.',
            'bri_syar' => 'PT. Bank BRISyariah',
            'btn' => 'PT. Bank Tabungan Negara (Persero)',
            'btn_syar' => 'PT. BTN (Persero) Syariah',
            'btpn' => 'PT. Bank Tabungan Pensiunan Nasional',
            'btpn_syar' => 'PT. Bank Tabungan Pensiunan Nasional S',
            'bukopin' => 'PT. Bukopin',
            'bukopin_syar' => 'PT. Bank Syariah Bukopin',
            'bumiputera' => 'PT. Bank Bumiputera',
            'bumi_artha' => 'PT. Bank Bumi Arta',
            'capital' => 'PT. Bank Capital Indonesia',
            'centratama' => 'PT. Centratama Nasional Bank',
            'chase' => 'JPMorgan Chase Bank NA',
            'china' => 'Bank of China Limited',
            'chinatrust' => 'PT. Bank Chinatrust Indonesia',
            'cimb' => 'PT. Bank CIMB Niaga Tbk.',
            'citibank' => 'Citibank NA',
            'commonwealth' => 'PT. Bank Commonwealth',
            'danamon' => 'PT. Bank Danamon Indonesia Tbk.',
            'dbs' => 'PT. Bank DBS Indonesia',
            'deutsche' => 'Deutsche Bank AG.',
            'dipo' => 'PT. Bank Dipo International',
            'diy' => 'PT. BPD DIY',
            'diy_syar' => 'PT. BPD DIY Syariah',
            'dki' => 'PT. BPD DKI Jakarta',
            'dki_syar' => 'PT. BPD DKI Jakarta Syariah',
            'fama' => 'PT. Bank Fama International',
            'ganesha' => 'PT. Bank Ganesha',
            'hana' => 'Bank Hana',
            'harda' => 'PT. Bank Harda International',
            'hsbc' => 'PT. Bank HSBC Indonesia',
            'hs_1906' => 'PT. Bank HS 1906',
            'icbc' => 'PT. Bank ICBC Indonesia',
            'ina_perdana' => 'PT. Bank Ina Perdana',
            'index_selindo' => 'PT. Bank Index Selindo',
            'jambi' => 'PT. BPD Jambi',
            'jasa_jakarta' => 'PT. Bank Jasa Jakarta',
            'jateng' => 'PT. BPD Jawa Tengah',
            'jateng_syar' => 'BPD Jateng Syariah',
            'jatim' => 'BPD Jawa Timur',
            'jatim_syar' => '   BPD Jatim Syariah',
            'jtrust' => 'PT. Bank JTrust Indonesia',
            'kalbar' => 'PT. BPD Kalimantan Barat',
            'kalbar_syar' => 'PT. BPD Kalimantan Barat Syariah',
            'kalsel' => 'BPD Kalimantan Selatan',
            'kalsel_syar' => 'BPD Kalimantan Selatan Syariah',
            'kalteng' => 'PT. BPD Kalteng',
            'kaltim' => 'PT. BPD Kalimantan Timur',
            'kaltim_syar' => 'PT. BPD Kalimantan Timur Syariah',
            'kesawan' => 'PT. Bank Kesawan',
            'kesejahteraan' => 'PT. Bank Kesejahteraan Ekonomi',
            'lampung' => 'BPD Lampung',
            'liman' => 'PT. Bank Liman International',
            'maluku' => 'PT. BPD Maluku',
            'mandiri' => 'PT. Bank Mandiri (Persero) Tbk.',
            'mandiri_syar' => 'PT. Bank Syariah Mandiri',
            'maspion' => 'PT. Bank Maspion Indonesia',
            'mayapada' => 'PT. Bank Mayapada',
            'maybank' => 'PT. BII Tbk.',
            'maybank_syar' => 'PT. BII Tbk. Syariah',
            'mayora' => 'PT. Bank Mayora Indonesia',
            'mega_syar' => 'PT. Bank Syariah Mega Indonesia',
            'mega_tbk' => 'PT. Bank Mega Tbk.',
            'mestika' => 'PT. Bank Mestika Dharma',
            'metro' => 'PT. Bank Metro Ekspress',
            'mitraniaga' => 'PT. Bank Mitraniaga',
            'mitsubishi' => 'The BoT Mitsubishi UFJ LTD.',
            'mizuho' => 'PT. Bank Mizuho Indonesia',
            'mnc' => 'PT. Bank MNC Internasional Tbk.',
            'muamalat' => 'PT. Bank Muamalat Indonesia',
            'multiarta' => 'PT. Bank Multiarta Sentosa',
            'mutiara' => 'PT. Bank Mutiara Tbk.',
            'niaga_syar' => 'PT. Bank Niaga Tbk. Syariah',
            'nobu' => 'PT. Bank National Nobu',
            'ntb' => 'PT. Bank Pembangunan Daerah NTB',
            'ntt' => 'BPD Nusa Tenggara Timur',
            'ocbc' => 'PT. Bank OCBC NISP Tbk.',
            'panin' => 'PT. Bank Panin Indonesia Tbk.',
            'panin_syar' => 'PT. Bank Panin Syariah',
            'papua' => 'PT. BPD Papua',
            'permata_syar' => 'PT. Bank Permata Tbk. Syariah',
            'prima_master' => 'PT. Prima Master Bank',
            'pundi' => 'PT. Bank Pundi Indonesia',
            'purba' => 'PT. Bank Purba Danarta',
            'rabobank' => 'PT. Bank Rabobank International I',
            'rbos' => 'The Royal Bank of Scotland N.V.',
            'resona' => 'PT. Bank Resona Perdania',
            'riau' => 'PT. BPD Riau',
            'royal' => 'PT. Bank Royal Indonesia',
            'sampoerna' => 'PT. Bank Sahabat Sampoerna',
            'sbi' => 'PT. Bank SBI Indonesia',
            'sinarmas' => 'PT. Bank Sinarmas',
            'sinarmas_syar' => 'PT. Bank Sinarmas Syariah',
            'sinar_bali' => 'PT. Bank Sinar Harapan Bali',
            'stanchard' => 'Standard Chartered Bank',
            'sulsel' => 'PT. BPD Sulawesi Selatan',
            'sulselbar' => 'PT. Bank Sulselbar Syariah',
            'sulteng' => 'PT. BPD Sulawesi Tengah',
            'sultenggara' => 'PT. BPD Sulawesi Tenggara',
            'sulut' => 'BPD Sulawesi Utara',
            'sumbar' => 'BPD Sumatera Barat',
            'sumitomo' => 'PT. Bank Sumitomo Mitsui Indonesia',
            'sumsel_babel' => 'BPD Sumsel dan Babel',
            'sumut' => 'BPD Sumatera Utara',
            'swadesi' => 'PT. Bank Swadesi Tbk.',
            'uob' => 'PT. Bank UOB Indonesia',
            'victoria' => 'PT. Bank Victoria International',
            'victoria_syar' => 'PT. Bank Victoria Syariah',
            'windu' => 'PT. Bank Windu Kentjana International',
            'woori' => '    PT. Bank Woori Indonesia',
            'yudha_bhakti' => 'PT. Bank Yudha Bhakti',
        ];
        foreach ($banks as $key => $value) {
            DB::table('banks')->insert([
                'name' => $value,
                'code' => $key,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ]);
        }
    }
}